"""Константы, специфичные для notify.a161.ru (не дублировать в корневом const.py)."""

from __future__ import annotations

from ...const import (
    RECEIVE_MODE_POLLING,
    RECEIVE_MODE_SEND_ONLY,
    UPDATE_MESSAGE_CALLBACK,
    UPDATE_MESSAGE_CREATED,
)

CONF_A161_POLLING_GRACE_STARTED_AT = "a161_polling_grace_started_at"
CONF_A161_LAST_BUTTON_SEND_AT = "a161_last_button_send_at"
CONF_A161_LAST_INCOMING_AT = "a161_last_incoming_at"
CONF_A161_INACTIVITY_PERIOD_DAYS = "a161_inactivity_period_days"

API_BASE_URL = "https://notify.a161.ru"
API_VERSION = "1.2.5"

ACCESS_TOKEN_EXPECTED_LENGTH = 36

UPDATE_TYPES_RECEIVE: tuple[str, ...] = (
    UPDATE_MESSAGE_CREATED,
    UPDATE_MESSAGE_CALLBACK,
)

RECEIVE_MODES: tuple[str, str] = (RECEIVE_MODE_SEND_ONLY, RECEIVE_MODE_POLLING)

NOTIFY_A161_MAX_UPLOAD_BYTES = 10 * 1024 * 1024
NOTIFY_A161_MIN_SEND_INTERVAL_SECONDS = 1.0
NOTIFY_A161_UPDATES_INTERVAL_SECONDS = 5
NOTIFY_A161_UPDATES_INTERVAL_MIN_SECONDS = 2
NOTIFY_A161_UPDATES_INTERVAL_MAX_SECONDS = 30
NOTIFY_A161_POLLING_GRACE_SECONDS = 24 * 60 * 60
NOTIFY_A161_UPDATES_LIMIT = 5
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_MIN = 1
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_MAX = 3
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_DEFAULT = 3

TITLE_FALLBACK_SUBSTRINGS: tuple[str, ...] = (
    "notify.a161.ru",
    "notify_a161",
    "maxnotify (notify",
)
