"""Константы, специфичные для notify.a161.ru (не дублировать в корневом const.py)."""

from __future__ import annotations

from ...const import (
    RECEIVE_MODE_POLLING,
    RECEIVE_MODE_SEND_ONLY,
    RECEIVE_MODE_WEBSOCKET,
    UPDATE_MESSAGE_CALLBACK,
    UPDATE_MESSAGE_CREATED,
)

CONF_A161_POLLING_GRACE_STARTED_AT = "a161_polling_grace_started_at"
CONF_A161_LAST_BUTTON_SEND_AT = "a161_last_button_send_at"
CONF_A161_LAST_INCOMING_AT = "a161_last_incoming_at"
CONF_A161_INACTIVITY_PERIOD_DAYS = "a161_inactivity_period_days"
# Переопределение URL WebSocket (прототип / dev, пока сервер не готов).
CONF_A161_WEBSOCKET_URL = "a161_websocket_url"

API_PATH_ME_CAPABILITIES = "/me/capabilities"

API_BASE_URL = "https://notify.a161.ru"
API_VERSION = "1.2.5"

ACCESS_TOKEN_EXPECTED_LENGTH = 36

UPDATE_TYPES_RECEIVE: tuple[str, ...] = (
    UPDATE_MESSAGE_CREATED,
    UPDATE_MESSAGE_CALLBACK,
)

RECEIVE_MODES: tuple[str, ...] = (
    RECEIVE_MODE_SEND_ONLY,
    RECEIVE_MODE_POLLING,
    RECEIVE_MODE_WEBSOCKET,
)

NOTIFY_A161_MAX_PHOTO_SIZE_MB = 4
NOTIFY_A161_MAX_VIDEO_SIZE_MB = 4
NOTIFY_A161_MAX_DOCUMENT_SIZE_MB = 4
NOTIFY_A161_MAX_UPLOAD_BYTES = NOTIFY_A161_MAX_PHOTO_SIZE_MB * 1024 * 1024
NOTIFY_A161_SMALL_FILE_MAX_SIZE_BYTES = 199_999
NOTIFY_A161_MAX_UPLOAD_REQUESTS_SMALL_FILE_PER_MINUTE = 15
NOTIFY_A161_MAX_UPLOAD_REQUESTS_PER_MINUTE = 2
# Взаимоисключающие лимиты исходящих сообщений (как в API: одно поле > 0, другое 0).
NOTIFY_A161_MAX_MESSAGE_PER_SECOND = 1
NOTIFY_A161_MAX_MESSAGE_PER_MINUTE = 0
NOTIFY_A161_MIN_SEND_INTERVAL_SECONDS = 1.0
NOTIFY_A161_POLLING_URL_DEFAULT = f"{API_BASE_URL}/updates"
NOTIFY_A161_POLLING_LIMIT = 5
NOTIFY_A161_POLLING_INTERVAL_DEFAULT_SECONDS = 5
NOTIFY_A161_POLLING_INTERVAL_MIN_SECONDS = 5
NOTIFY_A161_POLLING_INTERVAL_MAX_SECONDS = 360
# Алиасы для config flow / registry (совпадают с polling_* из capabilities).
NOTIFY_A161_UPDATES_INTERVAL_SECONDS = NOTIFY_A161_POLLING_INTERVAL_DEFAULT_SECONDS
NOTIFY_A161_UPDATES_INTERVAL_MIN_SECONDS = NOTIFY_A161_POLLING_INTERVAL_MIN_SECONDS
NOTIFY_A161_UPDATES_INTERVAL_MAX_SECONDS = NOTIFY_A161_POLLING_INTERVAL_MAX_SECONDS
NOTIFY_A161_UPDATES_LIMIT = NOTIFY_A161_POLLING_LIMIT
NOTIFY_A161_POLLING_GRACE_SECONDS = 24 * 60 * 60
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_MIN = 1
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_MAX = 3
NOTIFY_A161_INACTIVITY_PERIOD_DAYS_DEFAULT = 2

NOTIFY_A161_WEBSOCKET_URL_DEFAULT = "wss://notify.a161.ru/ws"
NOTIFY_A161_WEBSOCKET_HEARTBEAT_SECONDS = 30
NOTIFY_A161_WEBSOCKET_RECONNECT_MIN_SECONDS = 2
NOTIFY_A161_WEBSOCKET_RECONNECT_MAX_SECONDS = 120
# TTL кэша capabilities, если API не отдал refresh_capabilities / null / 0.
NOTIFY_A161_CAPABILITIES_CACHE_SECONDS = 24 * 60 * 60
# Интервал между GET /me/capabilities, если rate_limit_capabilities_per_minute нет / null / 0.
NOTIFY_A161_CAPABILITIES_RATE_DEFAULT_INTERVAL_SECONDS = 15 * 60
NOTIFY_A161_CAPABILITIES_HTTP_TIMEOUT = 15.0

TITLE_FALLBACK_SUBSTRINGS: tuple[str, ...] = (
    "notify.a161.ru",
    "notify_a161",
    "maxnotify (notify",
)
